name = "Rigo Craft"
author = "Erno Rigo"
version = "26.2-7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b98eeae72bcd41f07b0f1526893eecdea26cd48b2e8837cb203043227329830"

[versions]
minecraft = "26.2"
quilt = "0.30.1-beta.2"
