name = "RigoCraft"
author = "Erno Rigo"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49ba6addbdb4699fd931d97eed79ff4f50e07b8cebc01f6ec6ca7fdb339dc47b"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
