name = "RigoCraft"
author = "Erno Rigo"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc4ed665c05bd3fabff8acc1153597e48f22849d6e29d3fe0f049288a65e05cc"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
