name = "Rigo Craft"
author = "Erno Rigo"
version = "26.2-22"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df546134244d17286218ed36e5a0d8451d81bba82be597f8f2c7d79f78df7cc5"

[versions]
minecraft = "26.2"
quilt = "0.30.1-beta.2"
