name = "RigoCraft"
author = "Erno Rigo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b5c9063829ee92c3272e1ce999489afa016971d9cf6fc390dace25b29c5f90e"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
