name = "RigoCraft"
author = "Erno Rigo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f85f17467b62161c3908bac68400dd3fc79f9fe05848375017ac788f3492d5ca"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
