name = "RigoCraft"
author = "Erno Rigo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6356b8b482b6f78f1fb888d759e18b44d9a904f2985e2fd70a08884afcbbe8b0"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
