name = "Rigo Craft"
author = "Erno Rigo"
version = "26.2-20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4900ff67aa76ee9b7597d7f8d2566dff0a23f66e6ee768ae23b90b6127e31937"

[versions]
minecraft = "26.2"
quilt = "0.30.1-beta.2"
