name = "RigoCraft"
author = "Erno Rigo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e37de8bc2644d1a729bbf423e7e76a0c3407bf4ea38b899444ed2570b0b91e5"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
