name = "RigoCraft"
author = "Erno Rigo"
version = "1.0.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ad841596c7fde2995afdf7c445d0a5dffc5b08ea6cce3aeacb2f271136db0b4"

[versions]
minecraft = "1.20.1"
quilt = "0.23.0-beta.1"
