name = "RigoCraft"
author = "Erno Rigo"
version = "1.0.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6675d89cb31f68d862e8935f002218e8d57082f1cf93e446854edd78ddc44960"

[versions]
minecraft = "1.20.1"
quilt = "0.23.0-beta.1"
