name = "RigoCraft"
author = "Erno Rigo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1494a2a88bb90fa52b8219bca7accd22a172f197b1c83b193828cc44b5513d52"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
