name = "RigoCraft"
author = "Erno Rigo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8337d1ed778908bf54cac01c59123fa631f909079de8b02306f222369847fc6"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
