name = "RigoCraft"
author = "Erno Rigo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30407cb3f9c705138181acf5eea4713e3daf1543a266025441c7212424febf69"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
