name = "RigoCraft"
author = "Erno Rigo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28c0feb6c0eb736ace84929bc6282fe805d13d24bc743f53bc6aa68634a039ef"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
