name = "RigoCraft"
author = "Erno Rigo"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7bb855a08fbe0cf19ce77ef9e794d3fff57b1f82f2fc52999a83b9db82c3ab08"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
