name = "RigoCraft"
author = "Erno Rigo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d624eb76e3f41638e8353d37aa0ebeac3d5606a6d85669365964a8741dc2e418"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
