name = "RigoCraft"
author = "Erno Rigo"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d528605c3f3f33963896a608c2591ba393d02d428407c0b49a39f244f3ad7e2"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
