name = "RigoCraft"
author = "Erno Rigo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d14c46e3b9bf82433d31030e11095c2df882c86d7d3a6bc045b4fa57a64b636a"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.11"
