name = "RigoCraft"
author = "Erno Rigo"
version = "1.0.25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3df1227651db1d56767d0a4c33cf5879cc25aa50d479587596d6ceb5767e2f6"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0"
