name = "RigoCraft"
author = "Erno Rigo"
version = "1.0.17"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6bfb3417b354ecb01d485bad211e5f210263359469788404d6e8cd5cf9291856"

[versions]
minecraft = "1.20.1"
quilt = "0.23.0-beta.1"
